[Sun Jul 17 23:02:20.801928 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541] mod_wsgi (pid=2470): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module.
[Sun Jul 17 23:02:20.802528 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541] mod_wsgi (pid=2470): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Sun Jul 17 23:02:20.802550 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541] Traceback (most recent call last):
[Sun Jul 17 23:02:20.802570 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>
[Sun Jul 17 23:02:20.802635 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541]     from citadel import app as application
[Sun Jul 17 23:02:20.802680 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541]   File "/Users/jinho/Citadel/citadel.py", line 51
[Sun Jul 17 23:02:20.802687 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541]     user_id_validators =
[Sun Jul 17 23:02:20.802691 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541]                         ^
[Sun Jul 17 23:02:20.802695 2016] [wsgi:error] [pid 2470] [client 192.168.0.6:58541] SyntaxError: invalid syntax
[Tue Jul 19 14:39:09.158563 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348] mod_wsgi (pid=2482): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.165315 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.165460 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169685 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169738 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169799 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169818 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169848 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169863 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169888 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169902 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169925 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169939 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169962 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.169999 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.170026 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.170040 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.170063 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.170100 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/citadel.py", line 419, in show_thread, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.173124 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     return render_template('show_thread.html', thread=thread, messages=messages), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.173204 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.173913 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.173965 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.176673 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     return self.get_template(template_name_or_list, parent, globals), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.176728 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.176790 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     return self._load_template(name, self.make_globals(globals)), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.176809 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 786, in _load_template, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.176837 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     template = self.loader.load(self, name, globals), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.176859 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178320 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     code = environment.compile(source, name, filename), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178377 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178441 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     self.handle_exception(exc_info, source_hint=source_hint), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178461 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178513 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178532 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]   File "/Users/jinho/Citadel/templates/show_thread.html", line 99, in template, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.178687 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348]     {% ENDIF %}, referer: http://192.168.0.6:505/forums/unity/1
[Tue Jul 19 14:39:09.180512 2016] [wsgi:error] [pid 2482] [client 192.168.0.6:62348] TemplateSyntaxError: Encountered unknown tag 'ENDIF'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'., referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:38:58.481948 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869] mod_wsgi (pid=2483): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.482725 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869] Traceback (most recent call last):, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.482831 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487204 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487255 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487318 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487338 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487366 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487381 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487406 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487421 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487445 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487459 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487483 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487497 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487521 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487558 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487585 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.487601 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/citadel.py", line 419, in show_thread, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.488775 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     return render_template('show_thread.html', thread=thread, messages=messages), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.488834 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.489518 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     context, ctx.app), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.489570 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.489631 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     rv = template.render(context), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.489656 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492478 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     return self.environment.handle_exception(exc_info, True), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492528 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492591 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492609 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/templates/show_thread.html", line 3, in top-level template code, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492835 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     {% import 'macro_editor.html' as macro_editor %}, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492860 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1049, in module, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492896 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     self._module = rv = self.make_module(), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492912 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1033, in make_module, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492937 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     return TemplateModule(self, self.new_context(vars, shared, locals)), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492952 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1090, in __init__, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.492975 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     self._body_stream = list(template.root_render_func(context)), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.493013 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/templates/macro_editor.html", line 32, in top-level template code, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.493591 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     {% include '/static/pages/trex/test.html' %}, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.493634 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.493685 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     return self._get_source_fast(environment, template), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.493703 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.493821 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869]     raise TemplateNotFound(template), referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:38:58.494038 2016] [wsgi:error] [pid 2483] [client 192.168.0.6:53869] TemplateNotFound: /static/pages/trex/test.html, referer: http://192.168.0.6:505/thread/514
[Wed Jul 20 00:40:46.176674 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870] mod_wsgi (pid=2487): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.177112 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.177267 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180388 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180456 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180538 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180591 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180659 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180705 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180747 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180800 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180856 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.180900 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.181353 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.181379 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.181402 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.181414 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.181433 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.181444 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/citadel.py", line 419, in show_thread, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.182255 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     return render_template('show_thread.html', thread=thread, messages=messages), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.182288 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.182740 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     context, ctx.app), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.182764 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.182796 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     rv = template.render(context), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.182814 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184598 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     return self.environment.handle_exception(exc_info, True), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184625 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184659 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184672 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/templates/show_thread.html", line 3, in top-level template code, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184764 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     {% import 'macro_editor.html' as macro_editor %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184779 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1049, in module, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184801 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     self._module = rv = self.make_module(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184831 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1033, in make_module, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184852 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     return TemplateModule(self, self.new_context(vars, shared, locals)), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184863 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1090, in __init__, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184881 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     self._body_stream = list(template.root_render_func(context)), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.184891 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/templates/macro_editor.html", line 32, in top-level template code, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.185115 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     {% include '/static/pages/trex/test.html' %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.185131 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.185151 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     return self._get_source_fast(environment, template), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.185162 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.185179 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870]     raise TemplateNotFound(template), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 00:40:46.185315 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:53870] TemplateNotFound: /static/pages/trex/test.html, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.951550 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027] mod_wsgi (pid=2487): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.953698 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.953778 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.953994 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954017 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954064 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954081 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954108 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954123 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954803 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954849 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954882 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954899 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954924 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954938 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954963 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.954977 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955028 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955045 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/citadel.py", line 419, in show_thread, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955219 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     return render_template('show_thread.html', thread=thread, messages=messages), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955247 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955297 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     context, ctx.app), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955313 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955337 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     rv = template.render(context), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955356 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.955986 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     return self.environment.handle_exception(exc_info, True), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956038 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956106 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956126 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/templates/show_thread.html", line 4, in top-level template code, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956201 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     {% import 'macro_sh.html' as macro_sh %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956220 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/templates/layout.html", line 132, in top-level template code, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956417 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     {% block body %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956440 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/templates/show_thread.html", line 88, in block "body", referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956470 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     {{ macro_editor.form(name='add_message_editor', submit_url=url_for('add_message', thread_id=thread.id), submit_label='\xeb\x8c\x93\xea\xb8\x80 \xec\x9e\x85\xeb\xa0\xa5', submit_icon='glyphicon glyphicon-commentglyphicon glyphicon-comment', hide_cancel=True, initHeight=200) }}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.956490 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/templates/macro_editor.html", line 35, in template, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.957026 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     {% include '../static/pages/trex/test.html' %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.957051 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.957101 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     return self._get_source_fast(environment, template), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.957118 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.957144 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027]     raise TemplateNotFound(template), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:37.957330 2016] [wsgi:error] [pid 2487] [client 192.168.0.6:54027] TemplateNotFound: ../static/pages/trex/test.html, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.462291 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028] mod_wsgi (pid=3758): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.462533 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.462580 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466126 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466180 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466240 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466259 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466324 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466342 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466367 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466383 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466408 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466422 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466446 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466459 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466482 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466496 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466519 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.466534 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/citadel.py", line 419, in show_thread, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.467730 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     return render_template('show_thread.html', thread=thread, messages=messages), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.467791 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.468991 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     context, ctx.app), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.469047 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.469109 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     rv = template.render(context), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.469137 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471362 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     return self.environment.handle_exception(exc_info, True), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471432 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471495 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471515 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/templates/show_thread.html", line 4, in top-level template code, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471674 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     {% import 'macro_sh.html' as macro_sh %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471697 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/templates/layout.html", line 132, in top-level template code, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471839 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     {% block body %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471860 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/templates/show_thread.html", line 88, in block "body", referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471891 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     {{ macro_editor.form(name='add_message_editor', submit_url=url_for('add_message', thread_id=thread.id), submit_label='\xeb\x8c\x93\xea\xb8\x80 \xec\x9e\x85\xeb\xa0\xa5', submit_icon='glyphicon glyphicon-commentglyphicon glyphicon-comment', hide_cancel=True, initHeight=200) }}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.471910 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/templates/macro_editor.html", line 35, in template, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.472315 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     {% include '../static/pages/trex/test.html' %}, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.472339 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.472373 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     return self._get_source_fast(environment, template), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.472389 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.472414 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028]     raise TemplateNotFound(template), referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 01:03:40.472595 2016] [wsgi:error] [pid 3758] [client 192.168.0.6:54028] TemplateNotFound: ../static/pages/trex/test.html, referer: http://192.168.0.6:505/forums/unity/1
[Wed Jul 20 15:55:37.216135 2016] [wsgi:error] [pid 4875] [client ::1:54977] mod_wsgi (pid=4875): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.216737 2016] [wsgi:error] [pid 4875] [client ::1:54977] Traceback (most recent call last):, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.216816 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.220549 2016] [wsgi:error] [pid 4875] [client ::1:54977]     return self.wsgi_app(environ, start_response), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.220584 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.220937 2016] [wsgi:error] [pid 4875] [client ::1:54977]     response = self.make_response(self.handle_exception(e)), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.220956 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.220980 2016] [wsgi:error] [pid 4875] [client ::1:54977]     reraise(exc_type, exc_value, tb), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.220990 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221006 2016] [wsgi:error] [pid 4875] [client ::1:54977]     response = self.full_dispatch_request(), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221014 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221029 2016] [wsgi:error] [pid 4875] [client ::1:54977]     rv = self.handle_user_exception(e), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221037 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221050 2016] [wsgi:error] [pid 4875] [client ::1:54977]     reraise(exc_type, exc_value, tb), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221058 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221071 2016] [wsgi:error] [pid 4875] [client ::1:54977]     rv = self.dispatch_request(), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221079 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221093 2016] [wsgi:error] [pid 4875] [client ::1:54977]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.221105 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/citadel.py", line 211, in profile, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.225230 2016] [wsgi:error] [pid 4875] [client ::1:54977]     user = dbs.query(Member).filter(Member.id == session['user_info']['id']).one(), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.225270 2016] [wsgi:error] [pid 4875] [client ::1:54977]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2724, in one, referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.230424 2016] [wsgi:error] [pid 4875] [client ::1:54977]     raise orm_exc.NoResultFound("No row was found for one()"), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:37.230589 2016] [wsgi:error] [pid 4875] [client ::1:54977] NoResultFound: No row was found for one(), referer: http://localhost:505/forums/unity/1
[Wed Jul 20 15:55:59.285081 2016] [wsgi:error] [pid 4872] [client ::1:54981] mod_wsgi (pid=4872): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.285369 2016] [wsgi:error] [pid 4872] [client ::1:54981] Traceback (most recent call last):, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.285425 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296358 2016] [wsgi:error] [pid 4872] [client ::1:54981]     return self.wsgi_app(environ, start_response), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296410 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296470 2016] [wsgi:error] [pid 4872] [client ::1:54981]     response = self.make_response(self.handle_exception(e)), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296489 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296518 2016] [wsgi:error] [pid 4872] [client ::1:54981]     reraise(exc_type, exc_value, tb), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296533 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296558 2016] [wsgi:error] [pid 4872] [client ::1:54981]     response = self.full_dispatch_request(), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296573 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296598 2016] [wsgi:error] [pid 4872] [client ::1:54981]     rv = self.handle_user_exception(e), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296612 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296636 2016] [wsgi:error] [pid 4872] [client ::1:54981]     reraise(exc_type, exc_value, tb), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296649 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296673 2016] [wsgi:error] [pid 4872] [client ::1:54981]     rv = self.dispatch_request(), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296686 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296710 2016] [wsgi:error] [pid 4872] [client ::1:54981]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.296725 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/citadel.py", line 211, in profile, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.297938 2016] [wsgi:error] [pid 4872] [client ::1:54981]     user = dbs.query(Member).filter(Member.id == session['user_info']['id']).one(), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.297991 2016] [wsgi:error] [pid 4872] [client ::1:54981]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2724, in one, referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.303123 2016] [wsgi:error] [pid 4872] [client ::1:54981]     raise orm_exc.NoResultFound("No row was found for one()"), referer: http://localhost:505/thread/514
[Wed Jul 20 15:55:59.303359 2016] [wsgi:error] [pid 4872] [client ::1:54981] NoResultFound: No row was found for one(), referer: http://localhost:505/thread/514
[Fri Jul 22 16:09:39.743556 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285] mod_wsgi (pid=197): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module., referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.743693 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285] mod_wsgi (pid=197): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.743722 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285] Traceback (most recent call last):, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.743746 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.743831 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     from citadel import app as application, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.743854 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/citadel.py", line 14, in <module>, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.744070 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     from alchemy_citadel import Base, Member, Profile, Thread, Message, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.744089 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/alchemy_citadel.py", line 68, in <module>, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.744176 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     Base.metadata.create_all(engine), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.744193 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.746138 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     tables=tables), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.746172 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748357 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     with self._optional_conn_ctx_manager(connection) as conn:, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748400 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748559 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return self.gen.next(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748575 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748602 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     with self.contextual_connect() as conn:, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748612 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748626 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     self._wrap_pool_connect(self.pool.connect, None),, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748634 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748648 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     e, dialect, self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748669 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748727 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     exc_info, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748745 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748928 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     reraise(type(exception), exception, tb=exc_tb, cause=cause), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748947 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748975 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return fn(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.748988 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.749925 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return _ConnectionFairy._checkout(self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.749956 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.749993 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     fairy = _ConnectionRecord.checkout(pool), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750007 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750030 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     rec = pool._do_get(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750042 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750064 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     self._dec_overflow(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750076 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750876 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     compat.reraise(exc_type, exc_value, exc_tb), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750904 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750942 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return self._create_connection(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.750982 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751019 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return _ConnectionRecord(self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751074 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751127 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     self.connection = self.__connect(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751148 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751179 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     connection = self.__pool._invoke_creator(self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751197 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751467 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return dialect.connect(*cargs, **cparams), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.751501 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.752012 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return self.dbapi.connect(*cargs, **cparams), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.752033 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.752285 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     return Connection(*args, **kwargs), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.752309 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.752481 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285]     super(Connection, self).__init__(*args, **kwargs2), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:39.752539 2016] [wsgi:error] [pid 197] [client 192.168.0.6:49285] OperationalError: (_mysql_exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)"), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:09:40.745720 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286] mod_wsgi (pid=520): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module., referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.745929 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286] mod_wsgi (pid=520): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.745969 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746006 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746118 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     from citadel import app as application, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746141 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/citadel.py", line 14, in <module>, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746392 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     from alchemy_citadel import Base, Member, Profile, Thread, Message, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746438 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/alchemy_citadel.py", line 68, in <module>, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746534 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     Base.metadata.create_all(engine), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.746552 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.748164 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     tables=tables), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.748205 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749210 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     with self._optional_conn_ctx_manager(connection) as conn:, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749244 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749554 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return self.gen.next(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749586 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749626 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     with self.contextual_connect() as conn:, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749645 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749674 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     self._wrap_pool_connect(self.pool.connect, None),, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749692 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749765 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     e, dialect, self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749794 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749829 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     exc_info, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749846 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.749998 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     reraise(type(exception), exception, tb=exc_tb, cause=cause), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750021 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750077 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return fn(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750096 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750638 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return _ConnectionFairy._checkout(self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750660 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750690 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     fairy = _ConnectionRecord.checkout(pool), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750704 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750726 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     rec = pool._do_get(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750739 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750761 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     self._dec_overflow(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.750773 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751348 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     compat.reraise(exc_type, exc_value, exc_tb), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751374 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751412 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return self._create_connection(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751432 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751460 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return _ConnectionRecord(self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751476 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751500 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     self.connection = self.__connect(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751515 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751540 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     connection = self.__pool._invoke_creator(self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751556 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751743 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return dialect.connect(*cargs, **cparams), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.751765 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.752239 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return self.dbapi.connect(*cargs, **cparams), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.752267 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.752376 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     return Connection(*args, **kwargs), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.752397 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.752597 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286]     super(Connection, self).__init__(*args, **kwargs2), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:09:40.752671 2016] [wsgi:error] [pid 520] [client 192.168.0.6:49286] OperationalError: (_mysql_exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)"), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:55.834690 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335] mod_wsgi (pid=606): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module., referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.835143 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335] mod_wsgi (pid=606): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.835212 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335] Traceback (most recent call last):, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.835243 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.835357 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     from citadel import app as application, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.835376 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/citadel.py", line 14, in <module>, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.836459 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     from alchemy_citadel import Base, Member, Profile, Thread, Message, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.836508 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/alchemy_citadel.py", line 68, in <module>, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.837129 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     Base.metadata.create_all(engine), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.837164 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.841477 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     tables=tables), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.841532 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844167 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     with self._optional_conn_ctx_manager(connection) as conn:, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844234 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844536 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return self.gen.next(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844562 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844595 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     with self.contextual_connect() as conn:, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844606 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844621 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     self._wrap_pool_connect(self.pool.connect, None),, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844630 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844644 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     e, dialect, self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844656 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844735 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     exc_info, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.844751 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.845170 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     reraise(type(exception), exception, tb=exc_tb, cause=cause), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.845192 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.845221 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return fn(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.845252 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847225 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return _ConnectionFairy._checkout(self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847251 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847282 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     fairy = _ConnectionRecord.checkout(pool), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847291 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847321 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     rec = pool._do_get(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847331 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847345 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     self._dec_overflow(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.847353 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849180 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     compat.reraise(exc_type, exc_value, exc_tb), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849219 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849258 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return self._create_connection(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849269 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849286 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return _ConnectionRecord(self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849295 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849352 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     self.connection = self.__connect(), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849378 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849453 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     connection = self.__pool._invoke_creator(self), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.849483 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.850206 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return dialect.connect(*cargs, **cparams), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.850253 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.851575 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return self.dbapi.connect(*cargs, **cparams), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.851608 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.851938 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     return Connection(*args, **kwargs), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.851967 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__, referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.852896 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335]     super(Connection, self).__init__(*args, **kwargs2), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:55.852952 2016] [wsgi:error] [pid 606] [client 192.168.0.6:51335] OperationalError: (_mysql_exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)"), referer: http://192.168.0.6:505/thread/515
[Fri Jul 22 16:16:56.599331 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336] mod_wsgi (pid=608): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module., referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599432 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336] mod_wsgi (pid=608): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599453 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599474 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599547 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     from citadel import app as application, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599560 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/citadel.py", line 14, in <module>, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599707 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     from alchemy_citadel import Base, Member, Profile, Thread, Message, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599719 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/alchemy_citadel.py", line 68, in <module>, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599773 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     Base.metadata.create_all(engine), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.599784 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.600747 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     tables=tables), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.600761 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601339 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     with self._optional_conn_ctx_manager(connection) as conn:, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601360 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601486 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return self.gen.next(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601499 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601520 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     with self.contextual_connect() as conn:, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601528 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601561 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     self._wrap_pool_connect(self.pool.connect, None),, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601570 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601583 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     e, dialect, self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601591 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601604 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     exc_info, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601612 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601699 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     reraise(type(exception), exception, tb=exc_tb, cause=cause), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601710 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601725 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return fn(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.601738 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602086 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return _ConnectionFairy._checkout(self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602098 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602115 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     fairy = _ConnectionRecord.checkout(pool), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602123 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602136 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     rec = pool._do_get(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602144 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602157 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     self._dec_overflow(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602164 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602510 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     compat.reraise(exc_type, exc_value, exc_tb), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602524 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602553 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return self._create_connection(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602563 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602576 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return _ConnectionRecord(self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602584 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602596 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     self.connection = self.__connect(), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602612 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602636 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     connection = self.__pool._invoke_creator(self), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602644 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602840 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return dialect.connect(*cargs, **cparams), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.602862 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.603172 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return self.dbapi.connect(*cargs, **cparams), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.603195 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.603264 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     return Connection(*args, **kwargs), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.603276 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__, referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.603395 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336]     super(Connection, self).__init__(*args, **kwargs2), referer: http://192.168.0.6:505/forums/unity/1
[Fri Jul 22 16:16:56.603454 2016] [wsgi:error] [pid 608] [client 192.168.0.6:51336] OperationalError: (_mysql_exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)"), referer: http://192.168.0.6:505/forums/unity/1
