[Sat Jun 18 12:19:44.604537 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120] mod_wsgi (pid=9052): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.604715 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.604752 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608111 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608150 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608197 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608211 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608231 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608242 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608259 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608270 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608287 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608297 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608313 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608323 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608340 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608350 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608367 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608378 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]   File "/Users/jinho/Citadel/citadel.py", line 152, in show_thread, referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608490 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120]     messages = [alc2json(msg) for msg in thread.messages], referer: http://192.168.0.6:505/forums/unity
[Sat Jun 18 12:19:44.608537 2016] [wsgi:error] [pid 9052] [client 192.168.0.6:53120] AttributeError: 'dict' object has no attribute 'messages', referer: http://192.168.0.6:505/forums/unity
