[Tue Jun 28 19:30:10.906658 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377] mod_wsgi (pid=12547): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module.
[Tue Jun 28 19:30:10.906806 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377] mod_wsgi (pid=12547): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:30:10.906831 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377] Traceback (most recent call last):
[Tue Jun 28 19:30:10.906854 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>
[Tue Jun 28 19:30:10.906924 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377]     from citadel import app as application
[Tue Jun 28 19:30:10.906969 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377]   File "/Users/jinho/Citadel/citadel.py", line 324
[Tue Jun 28 19:30:10.906977 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377]     if (total_rows%page_rows) > 0:
[Tue Jun 28 19:30:10.906982 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377]     ^
[Tue Jun 28 19:30:10.906987 2016] [wsgi:error] [pid 12547] [client 192.168.0.6:63377] IndentationError: unexpected indent
[Tue Jun 28 19:30:16.880629 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380] mod_wsgi (pid=12556): Target WSGI script '/Users/jinho/Citadel/citadel.wsgi' cannot be loaded as Python module.
[Tue Jun 28 19:30:16.880744 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380] mod_wsgi (pid=12556): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:30:16.880762 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380] Traceback (most recent call last):
[Tue Jun 28 19:30:16.880781 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380]   File "/Users/jinho/Citadel/citadel.wsgi", line 9, in <module>
[Tue Jun 28 19:30:16.880837 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380]     from citadel import app as application
[Tue Jun 28 19:30:16.880874 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380]   File "/Users/jinho/Citadel/citadel.py", line 324
[Tue Jun 28 19:30:16.880880 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380]     if (total_rows%page_rows) > 0:
[Tue Jun 28 19:30:16.880884 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380]     ^
[Tue Jun 28 19:30:16.880887 2016] [wsgi:error] [pid 12556] [client 192.168.0.6:63380] IndentationError: unexpected indent
[Tue Jun 28 19:40:10.253157 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465] mod_wsgi (pid=12631): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.259542 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.259638 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.281826 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.281880 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.281940 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.281960 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.281987 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282023 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282052 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282068 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282091 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282106 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282129 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282143 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282166 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282180 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282202 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282217 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/citadel.py", line 338, in forum, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282442 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     threads = [(alc2json(thread), alc2json(thread.messages[0]), alc2json(thread.messages[0].author)) for thread in q], referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.282464 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.286428 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     return self._execute_and_instances(context), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.286479 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.286539 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     result = conn.execute(querycontext.statement, self._params), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.286559 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.289370 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     return meth(self, multiparams, params), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.289424 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293506 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     return connection._execute_clauseelement(self, multiparams, params), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293569 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293643 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     compiled_sql, distilled_params, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293657 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293680 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     context), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293691 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293709 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     exc_info, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.293719 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.294147 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     reraise(type(exception), exception, tb=exc_tb, cause=cause), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.294178 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.294221 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     context), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.294240 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.295734 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     cursor.execute(statement, parameters), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.295787 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.297431 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     self.errorhandler(self, exc, value), referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.297497 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.298431 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465]     raise errorclass, errorvalue, referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:10.298534 2016] [wsgi:error] [pid 12631] [client 192.168.0.6:63465] ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-40' at line 3") [SQL: u'SELECT thread.id AS thread_id, thread.title AS thread_title, thread.replies AS thread_replies, thread.views AS thread_views, thread.tags AS thread_tags \\nFROM thread \\n LIMIT %s, %s'] [parameters: (40, -40)], referer: http://192.168.0.6:505/forums/unity/4
[Tue Jun 28 19:40:37.506550 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477] mod_wsgi (pid=12650): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:40:37.512793 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477] Traceback (most recent call last):
[Tue Jun 28 19:40:37.512869 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Tue Jun 28 19:40:37.530915 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     return self.wsgi_app(environ, start_response)
[Tue Jun 28 19:40:37.530968 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Tue Jun 28 19:40:37.531029 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     response = self.make_response(self.handle_exception(e))
[Tue Jun 28 19:40:37.531048 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Tue Jun 28 19:40:37.531078 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:40:37.531092 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Tue Jun 28 19:40:37.531122 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     response = self.full_dispatch_request()
[Tue Jun 28 19:40:37.531137 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Tue Jun 28 19:40:37.531162 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     rv = self.handle_user_exception(e)
[Tue Jun 28 19:40:37.531175 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Tue Jun 28 19:40:37.531199 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:40:37.531212 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Tue Jun 28 19:40:37.531234 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     rv = self.dispatch_request()
[Tue Jun 28 19:40:37.531248 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Tue Jun 28 19:40:37.531271 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 28 19:40:37.531286 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/citadel.py", line 338, in forum
[Tue Jun 28 19:40:37.531525 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     threads = [(alc2json(thread), alc2json(thread.messages[0]), alc2json(thread.messages[0].author)) for thread in q]
[Tue Jun 28 19:40:37.531548 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
[Tue Jun 28 19:40:37.534178 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     return self._execute_and_instances(context)
[Tue Jun 28 19:40:37.534220 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
[Tue Jun 28 19:40:37.534273 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     result = conn.execute(querycontext.statement, self._params)
[Tue Jun 28 19:40:37.534292 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
[Tue Jun 28 19:40:37.536116 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     return meth(self, multiparams, params)
[Tue Jun 28 19:40:37.536156 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
[Tue Jun 28 19:40:37.538449 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     return connection._execute_clauseelement(self, multiparams, params)
[Tue Jun 28 19:40:37.538491 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
[Tue Jun 28 19:40:37.538546 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     compiled_sql, distilled_params
[Tue Jun 28 19:40:37.538564 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
[Tue Jun 28 19:40:37.538593 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     context)
[Tue Jun 28 19:40:37.538607 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
[Tue Jun 28 19:40:37.538632 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     exc_info
[Tue Jun 28 19:40:37.538645 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
[Tue Jun 28 19:40:37.539205 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[Tue Jun 28 19:40:37.539248 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
[Tue Jun 28 19:40:37.539302 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     context)
[Tue Jun 28 19:40:37.539320 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
[Tue Jun 28 19:40:37.540680 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     cursor.execute(statement, parameters)
[Tue Jun 28 19:40:37.540731 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
[Tue Jun 28 19:40:37.541962 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     self.errorhandler(self, exc, value)
[Tue Jun 28 19:40:37.542014 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
[Tue Jun 28 19:40:37.543083 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477]     raise errorclass, errorvalue
[Tue Jun 28 19:40:37.543231 2016] [wsgi:error] [pid 12650] [client 192.168.0.6:63477] ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-20' at line 3") [SQL: u'SELECT thread.id AS thread_id, thread.title AS thread_title, thread.replies AS thread_replies, thread.views AS thread_views, thread.tags AS thread_tags \\nFROM thread \\n LIMIT %s, %s'] [parameters: (20, -20)]
[Tue Jun 28 19:49:52.627661 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502] mod_wsgi (pid=12688): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:49:52.634057 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502] Traceback (most recent call last):
[Tue Jun 28 19:49:52.634184 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Tue Jun 28 19:49:52.646069 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     return self.wsgi_app(environ, start_response)
[Tue Jun 28 19:49:52.646121 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Tue Jun 28 19:49:52.646180 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     response = self.make_response(self.handle_exception(e))
[Tue Jun 28 19:49:52.646198 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Tue Jun 28 19:49:52.646227 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:49:52.646241 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Tue Jun 28 19:49:52.646265 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     response = self.full_dispatch_request()
[Tue Jun 28 19:49:52.646280 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Tue Jun 28 19:49:52.646303 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     rv = self.handle_user_exception(e)
[Tue Jun 28 19:49:52.646316 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Tue Jun 28 19:49:52.646340 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:49:52.646353 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Tue Jun 28 19:49:52.646375 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     rv = self.dispatch_request()
[Tue Jun 28 19:49:52.646389 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Tue Jun 28 19:49:52.646417 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 28 19:49:52.646434 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]   File "/Users/jinho/Citadel/citadel.py", line 328, in forum
[Tue Jun 28 19:49:52.646704 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502]     cur_page_idx = min(page_idx, total_page-1)
[Tue Jun 28 19:49:52.646745 2016] [wsgi:error] [pid 12688] [client 192.168.0.6:63502] NameError: global name 'total_page' is not defined
[Tue Jun 28 19:51:45.981802 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509] mod_wsgi (pid=12696): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:51:45.981848 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509] Traceback (most recent call last):
[Tue Jun 28 19:51:45.981868 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Tue Jun 28 19:51:45.995683 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     return self.wsgi_app(environ, start_response)
[Tue Jun 28 19:51:45.995733 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Tue Jun 28 19:51:45.995793 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     response = self.make_response(self.handle_exception(e))
[Tue Jun 28 19:51:45.995812 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Tue Jun 28 19:51:45.995870 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:51:45.995887 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Tue Jun 28 19:51:45.995911 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     response = self.full_dispatch_request()
[Tue Jun 28 19:51:45.995925 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Tue Jun 28 19:51:45.995948 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     rv = self.handle_user_exception(e)
[Tue Jun 28 19:51:45.995961 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Tue Jun 28 19:51:45.995984 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:51:45.995997 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Tue Jun 28 19:51:45.996019 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     rv = self.dispatch_request()
[Tue Jun 28 19:51:45.996032 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Tue Jun 28 19:51:45.996061 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 28 19:51:45.996077 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]   File "/Users/jinho/Citadel/citadel.py", line 328, in forum
[Tue Jun 28 19:51:45.996348 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509]     cur_page_idx = min(page_idx, total_page-1)
[Tue Jun 28 19:51:45.996390 2016] [wsgi:error] [pid 12696] [client 192.168.0.6:63509] NameError: global name 'total_page' is not defined
[Tue Jun 28 19:52:40.977847 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510] mod_wsgi (pid=12704): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:52:40.977892 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510] Traceback (most recent call last):
[Tue Jun 28 19:52:40.977916 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Tue Jun 28 19:52:40.978612 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     return self.wsgi_app(environ, start_response)
[Tue Jun 28 19:52:40.978631 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Tue Jun 28 19:52:40.978657 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     response = self.make_response(self.handle_exception(e))
[Tue Jun 28 19:52:40.978669 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Tue Jun 28 19:52:40.978687 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:52:40.978698 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Tue Jun 28 19:52:40.978715 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     response = self.full_dispatch_request()
[Tue Jun 28 19:52:40.978724 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Tue Jun 28 19:52:40.978741 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     rv = self.handle_user_exception(e)
[Tue Jun 28 19:52:40.978775 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Tue Jun 28 19:52:40.978794 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:52:40.978804 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Tue Jun 28 19:52:40.978821 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     rv = self.dispatch_request()
[Tue Jun 28 19:52:40.978831 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Tue Jun 28 19:52:40.978847 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 28 19:52:40.978857 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]   File "/Users/jinho/Citadel/citadel.py", line 328, in forum
[Tue Jun 28 19:52:40.979002 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510]     cur_page_idx = min(page_idx, max(0, total_page-1))
[Tue Jun 28 19:52:40.979026 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63510] NameError: global name 'total_page' is not defined
[Tue Jun 28 19:53:21.073295 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515] mod_wsgi (pid=12704): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Tue Jun 28 19:53:21.073669 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515] Traceback (most recent call last):
[Tue Jun 28 19:53:21.073723 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Tue Jun 28 19:53:21.073906 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     return self.wsgi_app(environ, start_response)
[Tue Jun 28 19:53:21.073918 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Tue Jun 28 19:53:21.073935 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     response = self.make_response(self.handle_exception(e))
[Tue Jun 28 19:53:21.073953 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Tue Jun 28 19:53:21.073983 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:53:21.073991 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Tue Jun 28 19:53:21.074005 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     response = self.full_dispatch_request()
[Tue Jun 28 19:53:21.074012 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Tue Jun 28 19:53:21.074025 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     rv = self.handle_user_exception(e)
[Tue Jun 28 19:53:21.074032 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Tue Jun 28 19:53:21.074045 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     reraise(exc_type, exc_value, tb)
[Tue Jun 28 19:53:21.074052 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Tue Jun 28 19:53:21.074064 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     rv = self.dispatch_request()
[Tue Jun 28 19:53:21.074071 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Tue Jun 28 19:53:21.074110 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 28 19:53:21.074119 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]   File "/Users/jinho/Citadel/citadel.py", line 328, in forum
[Tue Jun 28 19:53:21.075160 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515]     cur_page_idx = min(page_idx, max(0, total_pages-1))
[Tue Jun 28 19:53:21.075369 2016] [wsgi:error] [pid 12704] [client 192.168.0.6:63515] NameError: global name 'total_page' is not defined
[Wed Jun 29 11:21:58.772307 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115] mod_wsgi (pid=12752): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'., referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.784123 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115] Traceback (most recent call last):, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.784313 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826060 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     return self.wsgi_app(environ, start_response), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826098 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826143 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     response = self.make_response(self.handle_exception(e)), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826157 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826176 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826186 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826202 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     response = self.full_dispatch_request(), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826211 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826226 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     rv = self.handle_user_exception(e), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826234 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826248 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826257 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826271 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     rv = self.dispatch_request(), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826279 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826309 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.826320 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.828921 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.829001 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.830482 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     context, ctx.app), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.830517 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.830570 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     rv = template.render(context), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.830595 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.833983 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     return self.environment.handle_exception(exc_info, True), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.834023 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.834075 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     reraise(exc_type, exc_value, tb), referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.834090 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/templates/forum.html", line 1, in top-level template code, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.834163 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     {%extends "layout.html"%}, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.834181 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/templates/layout.html", line 85, in top-level template code, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.835543 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     {% block body %}, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.835570 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in block "body", referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.835602 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115]     {% for n in range(max(3, total_pages)) %}, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:21:58.835707 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65115] UndefinedError: 'max' is undefined, referer: http://192.168.0.6:505/forums/unity/5
[Wed Jun 29 11:26:05.388139 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198] mod_wsgi (pid=12756): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:26:05.388697 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198] Traceback (most recent call last):
[Wed Jun 29 11:26:05.388820 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:26:05.391785 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:26:05.391833 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:26:05.391892 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:26:05.391911 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:26:05.391942 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:26:05.391956 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:26:05.391981 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     response = self.full_dispatch_request()
[Wed Jun 29 11:26:05.391996 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:26:05.392019 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:26:05.392032 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:26:05.392055 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:26:05.392068 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:26:05.392091 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     rv = self.dispatch_request()
[Wed Jun 29 11:26:05.392104 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:26:05.392126 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:26:05.392141 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum
[Wed Jun 29 11:26:05.393377 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx)
[Wed Jun 29 11:26:05.393436 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
[Wed Jun 29 11:26:05.394068 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Wed Jun 29 11:26:05.394128 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
[Wed Jun 29 11:26:05.396126 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     return self.get_template(template_name_or_list, parent, globals)
[Wed Jun 29 11:26:05.396188 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
[Wed Jun 29 11:26:05.396292 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     return self._load_template(name, self.make_globals(globals))
[Wed Jun 29 11:26:05.396316 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 786, in _load_template
[Wed Jun 29 11:26:05.396375 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     template = self.loader.load(self, name, globals)
[Wed Jun 29 11:26:05.396401 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
[Wed Jun 29 11:26:05.397515 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     code = environment.compile(source, name, filename)
[Wed Jun 29 11:26:05.397558 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
[Wed Jun 29 11:26:05.397612 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     self.handle_exception(exc_info, source_hint=source_hint)
[Wed Jun 29 11:26:05.397631 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:26:05.397666 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:26:05.397683 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in template
[Wed Jun 29 11:26:05.397787 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198]     {% for n in range(cur_page_idx, 3)) %}
[Wed Jun 29 11:26:05.398042 2016] [wsgi:error] [pid 12756] [client 192.168.0.6:65198] TemplateSyntaxError: unexpected ')'
[Wed Jun 29 11:27:24.022790 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240] mod_wsgi (pid=12754): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:27:24.022945 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240] Traceback (most recent call last):
[Wed Jun 29 11:27:24.022968 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:27:24.025373 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:27:24.025410 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:27:24.025450 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:27:24.025462 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:27:24.025479 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:27:24.025487 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:27:24.025501 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     response = self.full_dispatch_request()
[Wed Jun 29 11:27:24.025510 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:27:24.025524 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:27:24.025532 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:27:24.025546 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:27:24.025554 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:27:24.025583 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     rv = self.dispatch_request()
[Wed Jun 29 11:27:24.025593 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:27:24.025607 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:27:24.025616 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum
[Wed Jun 29 11:27:24.026406 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx)
[Wed Jun 29 11:27:24.026443 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
[Wed Jun 29 11:27:24.027179 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Wed Jun 29 11:27:24.027208 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
[Wed Jun 29 11:27:24.028757 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     return self.get_template(template_name_or_list, parent, globals)
[Wed Jun 29 11:27:24.028801 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
[Wed Jun 29 11:27:24.028843 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     return self._load_template(name, self.make_globals(globals))
[Wed Jun 29 11:27:24.028857 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 786, in _load_template
[Wed Jun 29 11:27:24.028879 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     template = self.loader.load(self, name, globals)
[Wed Jun 29 11:27:24.028891 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
[Wed Jun 29 11:27:24.029662 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     code = environment.compile(source, name, filename)
[Wed Jun 29 11:27:24.029687 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
[Wed Jun 29 11:27:24.029717 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     self.handle_exception(exc_info, source_hint=source_hint)
[Wed Jun 29 11:27:24.029728 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:27:24.029744 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:27:24.029754 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in template
[Wed Jun 29 11:27:24.029815 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240]     {% for n in range(cur_page_idx, cur_page_idx+3)) %}
[Wed Jun 29 11:27:24.029879 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65240] TemplateSyntaxError: unexpected ')'
[Wed Jun 29 11:27:27.602882 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241] mod_wsgi (pid=12752): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:27:27.602976 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241] Traceback (most recent call last):
[Wed Jun 29 11:27:27.603018 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:27:27.603108 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:27:27.603119 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:27:27.603139 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:27:27.603147 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:27:27.603161 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:27:27.603168 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:27:27.603180 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     response = self.full_dispatch_request()
[Wed Jun 29 11:27:27.603187 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:27:27.603199 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:27:27.603206 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:27:27.603218 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:27:27.603224 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:27:27.603236 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     rv = self.dispatch_request()
[Wed Jun 29 11:27:27.603243 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:27:27.603257 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:27:27.603264 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum
[Wed Jun 29 11:27:27.603424 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx)
[Wed Jun 29 11:27:27.603438 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
[Wed Jun 29 11:27:27.603455 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Wed Jun 29 11:27:27.603465 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
[Wed Jun 29 11:27:27.603481 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     return self.get_template(template_name_or_list, parent, globals)
[Wed Jun 29 11:27:27.603489 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
[Wed Jun 29 11:27:27.603502 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     return self._load_template(name, self.make_globals(globals))
[Wed Jun 29 11:27:27.603510 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 786, in _load_template
[Wed Jun 29 11:27:27.603533 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     template = self.loader.load(self, name, globals)
[Wed Jun 29 11:27:27.603543 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
[Wed Jun 29 11:27:27.603680 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     code = environment.compile(source, name, filename)
[Wed Jun 29 11:27:27.603690 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
[Wed Jun 29 11:27:27.603708 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     self.handle_exception(exc_info, source_hint=source_hint)
[Wed Jun 29 11:27:27.603715 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:27:27.603729 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:27:27.603736 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in template
[Wed Jun 29 11:27:27.603784 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241]     {% for n in range(cur_page_idx, cur_page_idx+3)) %}
[Wed Jun 29 11:27:27.603894 2016] [wsgi:error] [pid 12752] [client 192.168.0.6:65241] TemplateSyntaxError: unexpected ')'
[Wed Jun 29 11:35:01.737585 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288] mod_wsgi (pid=12754): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:35:01.737696 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288] Traceback (most recent call last):
[Wed Jun 29 11:35:01.737753 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:35:01.737855 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:35:01.737869 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:35:01.737893 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:35:01.737904 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:35:01.737922 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:35:01.737932 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:35:01.737949 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     response = self.full_dispatch_request()
[Wed Jun 29 11:35:01.737959 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:35:01.737975 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:35:01.737985 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:35:01.738001 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:35:01.738010 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:35:01.738026 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     rv = self.dispatch_request()
[Wed Jun 29 11:35:01.738415 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:35:01.738460 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:35:01.738475 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum
[Wed Jun 29 11:35:01.738497 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx)
[Wed Jun 29 11:35:01.738512 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Wed Jun 29 11:35:01.738535 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     context, ctx.app)
[Wed Jun 29 11:35:01.738546 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
[Wed Jun 29 11:35:01.738562 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     rv = template.render(context)
[Wed Jun 29 11:35:01.738575 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
[Wed Jun 29 11:35:01.738596 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     return self.environment.handle_exception(exc_info, True)
[Wed Jun 29 11:35:01.738606 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:35:01.738625 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:35:01.738635 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/templates/forum.html", line 1, in top-level template code
[Wed Jun 29 11:35:01.738738 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     {%extends "layout.html"%}
[Wed Jun 29 11:35:01.738754 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/templates/layout.html", line 85, in top-level template code
[Wed Jun 29 11:35:01.738834 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     {% block body %}
[Wed Jun 29 11:35:01.738847 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in block "body"
[Wed Jun 29 11:35:01.738865 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288]     {% for n in range(cur_page_idx/3, cur_page_idx/3 + 3) %}
[Wed Jun 29 11:35:01.738955 2016] [wsgi:error] [pid 12754] [client 192.168.0.6:65288] TypeError: integer argument expected, got float
[Wed Jun 29 11:35:38.956645 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296] mod_wsgi (pid=12757): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:35:38.956743 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296] Traceback (most recent call last):
[Wed Jun 29 11:35:38.956808 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:35:38.960223 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:35:38.960281 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:35:38.960345 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:35:38.960364 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:35:38.960421 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:35:38.960438 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:35:38.960465 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     response = self.full_dispatch_request()
[Wed Jun 29 11:35:38.960480 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:35:38.960504 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:35:38.960518 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:35:38.960542 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:35:38.960555 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:35:38.960579 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     rv = self.dispatch_request()
[Wed Jun 29 11:35:38.960592 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:35:38.960615 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:35:38.960630 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum
[Wed Jun 29 11:35:38.961712 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx)
[Wed Jun 29 11:35:38.961770 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Wed Jun 29 11:35:38.962970 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     context, ctx.app)
[Wed Jun 29 11:35:38.963027 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
[Wed Jun 29 11:35:38.963089 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     rv = template.render(context)
[Wed Jun 29 11:35:38.963117 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
[Wed Jun 29 11:35:38.965281 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     return self.environment.handle_exception(exc_info, True)
[Wed Jun 29 11:35:38.965326 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:35:38.965381 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:35:38.965400 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/templates/forum.html", line 1, in top-level template code
[Wed Jun 29 11:35:38.965528 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     {%extends "layout.html"%}
[Wed Jun 29 11:35:38.965550 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/templates/layout.html", line 85, in top-level template code
[Wed Jun 29 11:35:38.965667 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     {% block body %}
[Wed Jun 29 11:35:38.965687 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in block "body"
[Wed Jun 29 11:35:38.965739 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296]     {% for n in range(int(cur_page_idx/3), int(cur_page_idx)/3 + 3) %}
[Wed Jun 29 11:35:38.965860 2016] [wsgi:error] [pid 12757] [client 192.168.0.6:65296] UndefinedError: 'int' is undefined
[Wed Jun 29 11:49:44.642343 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332] mod_wsgi (pid=13515): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:49:44.642474 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332] Traceback (most recent call last):
[Wed Jun 29 11:49:44.642496 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:49:44.645180 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:49:44.645225 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:49:44.645276 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:49:44.645290 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:49:44.645312 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:49:44.645323 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:49:44.645341 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     response = self.full_dispatch_request()
[Wed Jun 29 11:49:44.645352 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:49:44.645370 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:49:44.645381 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:49:44.645398 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:49:44.645408 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:49:44.645425 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     rv = self.dispatch_request()
[Wed Jun 29 11:49:44.645436 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:49:44.645455 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:49:44.645466 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/citadel.py", line 341, in forum
[Wed Jun 29 11:49:44.645688 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     return render_template('forum.html', name=name, threads=threads, total_pages=total_pages, cur_page_idx=cur_page_idx)
[Wed Jun 29 11:49:44.645707 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Wed Jun 29 11:49:44.646177 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     context, ctx.app)
[Wed Jun 29 11:49:44.646204 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
[Wed Jun 29 11:49:44.646251 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     rv = template.render(context)
[Wed Jun 29 11:49:44.646266 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
[Wed Jun 29 11:49:44.648167 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     return self.environment.handle_exception(exc_info, True)
[Wed Jun 29 11:49:44.648210 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:49:44.648259 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:49:44.648275 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/templates/forum.html", line 1, in top-level template code
[Wed Jun 29 11:49:44.648371 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     {%extends "layout.html"%}
[Wed Jun 29 11:49:44.648390 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/templates/layout.html", line 85, in top-level template code
[Wed Jun 29 11:49:44.648489 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     {% block body %}
[Wed Jun 29 11:49:44.648506 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in block "body"
[Wed Jun 29 11:49:44.648531 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332]     {% for n in range(cur_page_idx/3, cur_page_idx/3 + 3) %}
[Wed Jun 29 11:49:44.648562 2016] [wsgi:error] [pid 13515] [client 192.168.0.6:65332] TypeError: integer argument expected, got float
[Wed Jun 29 11:50:21.349898 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337] mod_wsgi (pid=13513): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 11:50:21.350926 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337] Traceback (most recent call last):
[Wed Jun 29 11:50:21.350975 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 11:50:21.353787 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 11:50:21.353841 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 11:50:21.353902 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 11:50:21.353921 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 11:50:21.353951 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:50:21.353967 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 11:50:21.353993 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     response = self.full_dispatch_request()
[Wed Jun 29 11:50:21.354009 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 11:50:21.354033 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     rv = self.handle_user_exception(e)
[Wed Jun 29 11:50:21.354048 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 11:50:21.354072 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:50:21.354086 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 11:50:21.354143 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     rv = self.dispatch_request()
[Wed Jun 29 11:50:21.354162 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 11:50:21.354186 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 11:50:21.354203 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/citadel.py", line 335, in forum
[Wed Jun 29 11:50:21.355128 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     last_row_idx = min(first_row_idx + page_rows, total_rows)
[Wed Jun 29 11:50:21.355168 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Wed Jun 29 11:50:21.355727 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     context, ctx.app)
[Wed Jun 29 11:50:21.355774 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
[Wed Jun 29 11:50:21.355832 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     rv = template.render(context)
[Wed Jun 29 11:50:21.355851 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
[Wed Jun 29 11:50:21.357911 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     return self.environment.handle_exception(exc_info, True)
[Wed Jun 29 11:50:21.357962 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Jun 29 11:50:21.358023 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 11:50:21.358042 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/templates/forum.html", line 1, in top-level template code
[Wed Jun 29 11:50:21.358155 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     {%extends "layout.html"%}
[Wed Jun 29 11:50:21.358178 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/templates/layout.html", line 85, in top-level template code
[Wed Jun 29 11:50:21.358327 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     {% block body %}
[Wed Jun 29 11:50:21.358349 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]   File "/Users/jinho/Citadel/templates/forum.html", line 11, in block "body"
[Wed Jun 29 11:50:21.358380 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337]     {% for n in range(int(cur_page_idx)/3, 3) %}
[Wed Jun 29 11:50:21.358422 2016] [wsgi:error] [pid 13513] [client 192.168.0.6:65337] UndefinedError: 'int' is undefined
[Wed Jun 29 12:13:29.427039 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758] mod_wsgi (pid=13615): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 12:13:29.427164 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758] Traceback (most recent call last):
[Wed Jun 29 12:13:29.427183 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 12:13:29.430104 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 12:13:29.430141 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 12:13:29.430184 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 12:13:29.430211 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 12:13:29.430232 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:13:29.430255 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 12:13:29.430274 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     response = self.full_dispatch_request()
[Wed Jun 29 12:13:29.430285 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 12:13:29.430302 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     rv = self.handle_user_exception(e)
[Wed Jun 29 12:13:29.430312 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 12:13:29.430330 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:13:29.430339 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 12:13:29.430356 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     rv = self.dispatch_request()
[Wed Jun 29 12:13:29.430366 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 12:13:29.430383 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 12:13:29.430394 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/citadel.py", line 356, in main
[Wed Jun 29 12:13:29.430578 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     return redirect(url_for('forum', name='unity', page_idx=0))
[Wed Jun 29 12:13:29.430594 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/helpers.py", line 332, in url_for
[Wed Jun 29 12:13:29.432202 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     return appctx.app.handle_url_build_error(error, endpoint, values)
[Wed Jun 29 12:13:29.432243 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1811, in handle_url_build_error
[Wed Jun 29 12:13:29.432307 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:13:29.432324 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/helpers.py", line 322, in url_for
[Wed Jun 29 12:13:29.432352 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     force_external=external)
[Wed Jun 29 12:13:29.432366 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
[Wed Jun 29 12:13:29.434887 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758]     raise BuildError(endpoint, values, method, self)
[Wed Jun 29 12:13:29.435010 2016] [wsgi:error] [pid 13615] [client 192.168.0.6:49758] BuildError: Could not build url for endpoint 'forum' with values ['name', 'page_idx']. Did you forget to specify values ['page']?
[Wed Jun 29 12:14:12.513852 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783] mod_wsgi (pid=13623): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 12:14:12.513977 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783] Traceback (most recent call last):
[Wed Jun 29 12:14:12.514013 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 12:14:12.514570 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 12:14:12.514583 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 12:14:12.514602 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 12:14:12.514610 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 12:14:12.514623 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:14:12.514630 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 12:14:12.514642 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     response = self.full_dispatch_request()
[Wed Jun 29 12:14:12.514649 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 12:14:12.514661 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     rv = self.handle_user_exception(e)
[Wed Jun 29 12:14:12.514668 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 12:14:12.514680 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:14:12.514687 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 12:14:12.514698 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     rv = self.dispatch_request()
[Wed Jun 29 12:14:12.514705 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 12:14:12.514716 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 12:14:12.514724 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/citadel.py", line 356, in main
[Wed Jun 29 12:14:12.514833 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     return redirect(url_for('forum', name='unity', page_idx=0))
[Wed Jun 29 12:14:12.514843 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/helpers.py", line 332, in url_for
[Wed Jun 29 12:14:12.515092 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     return appctx.app.handle_url_build_error(error, endpoint, values)
[Wed Jun 29 12:14:12.515102 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1811, in handle_url_build_error
[Wed Jun 29 12:14:12.515117 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:14:12.515125 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/helpers.py", line 322, in url_for
[Wed Jun 29 12:14:12.515137 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     force_external=external)
[Wed Jun 29 12:14:12.515144 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
[Wed Jun 29 12:14:12.515613 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783]     raise BuildError(endpoint, values, method, self)
[Wed Jun 29 12:14:12.515657 2016] [wsgi:error] [pid 13623] [client 192.168.0.6:49783] BuildError: Could not build url for endpoint 'forum' with values ['name', 'page_idx']. Did you forget to specify values ['page']?
[Wed Jun 29 12:15:03.770132 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811] mod_wsgi (pid=13648): Exception occurred processing WSGI script '/Users/jinho/Citadel/citadel.wsgi'.
[Wed Jun 29 12:15:03.770300 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811] Traceback (most recent call last):
[Wed Jun 29 12:15:03.770329 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
[Wed Jun 29 12:15:03.789310 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     return self.wsgi_app(environ, start_response)
[Wed Jun 29 12:15:03.789363 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
[Wed Jun 29 12:15:03.789423 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     response = self.make_response(self.handle_exception(e))
[Wed Jun 29 12:15:03.789442 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
[Wed Jun 29 12:15:03.789470 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:15:03.789484 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Jun 29 12:15:03.789509 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     response = self.full_dispatch_request()
[Wed Jun 29 12:15:03.789524 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Jun 29 12:15:03.789559 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     rv = self.handle_user_exception(e)
[Wed Jun 29 12:15:03.789569 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Jun 29 12:15:03.789585 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     reraise(exc_type, exc_value, tb)
[Wed Jun 29 12:15:03.789594 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Jun 29 12:15:03.789610 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     rv = self.dispatch_request()
[Wed Jun 29 12:15:03.789620 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Jun 29 12:15:03.789640 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 29 12:15:03.789651 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]   File "/Users/jinho/Citadel/citadel.py", line 333, in forum
[Wed Jun 29 12:15:03.789848 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811]     cur_page_idx = min(int(page-1), max(0, total_pages-1))
[Wed Jun 29 12:15:03.789879 2016] [wsgi:error] [pid 13648] [client 192.168.0.6:49811] TypeError: unsupported operand type(s) for -: 'unicode' and 'int'
